import SpaceFooter from "@/components/main/Footer";
import SpaceNavbar from "@/components/main/Navbar";
import { StarsCanvas } from "@/components/main/Star-Background";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export const viewport = {
  themeColor: "#030014",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-[#030014] overflow-y-scroll overflow-x-hidden",
          inter.className
        )}
      >
        <StarsCanvas />
        <SpaceNavbar className="fixed top-0 left-0 right-0 z-50" />
        {children}
        <SpaceFooter suppressHydrationWarning />
      </body>
    </html>
  );
}
