import SpaceNavbar from "@/components/main/Navbar";
import { StarsCanvas } from "@/components/main/Star-Background";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export const viewport = {
  themeColor: "#030014",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-[#030014] overflow-y-scroll overflow-x-hidden",
          inter.className
        )}
      >
        <StarsCanvas />
        <SpaceNavbar />
        {children}
      </body>
    </html>
  );
}
